services:
 db:
    container_name: db
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: meetups-db
    ports:
      - "5433:5432"